trigger:
  branches:
    include:
    - master
  tags:
    include:
    - 0.*

pr:
  autoCancel: true

stages:
  - stage: Test
    jobs:
      - job: BasicTests
        strategy:
          matrix:
            Python36Ubuntu:
              imageName: 'ubuntu-latest'
              python.version: 3.6
            Python37Ubuntu:
              imageName: 'ubuntu-latest'
              python.version: 3.7
        steps:
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add Conda to path

          - bash: |
              conda config --set always_yes yes --set changeps1 no
              conda config --add channels conda-forge

          - bash: |
              conda update -c defaults conda
              conda update --all
              conda create -n test-environment
              source activate test-environment
              conda install --yes python=$(python.version) --file requirements-test.txt
              pip install -e .
            displayName: Create Conda env, Activate, Install dependencies, Install Branch

          - bash: |
              source activate test-environment
              python -m pytest -v template_python_package
            displayName: Run Tests
